
CREATE TABLE public."Answers" (
    id integer NOT NULL,
    "AnswerText" text NOT NULL,
    "QuestionId" integer NOT NULL
);


ALTER TABLE public."Answers" OWNER TO postgres;

ALTER TABLE public."Answers" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Answers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public."Interviews" (
    id integer NOT NULL,
    "UserName" text NOT NULL,
    "SurveyId" integer NOT NULL
);


ALTER TABLE public."Interviews" OWNER TO postgres;

ALTER TABLE public."Interviews" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Interviews_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public."Questions" (
    id integer NOT NULL,
    "QuestionText" text NOT NULL,
    "NextQuestionId" integer,
    "SurveyId" integer NOT NULL,
    "ResultId" integer
);


ALTER TABLE public."Questions" OWNER TO postgres;


ALTER TABLE public."Questions" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Questions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."Results" (
    id integer NOT NULL,
    "InterviewId" integer NOT NULL,
    "QuestionId" integer NOT NULL,
    "AnswerId" integer NOT NULL
);


ALTER TABLE public."Results" OWNER TO postgres;

ALTER TABLE public."Results" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Results_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public."Surveys" (
    id integer NOT NULL,
    "SurveyText" text NOT NULL
);


ALTER TABLE public."Surveys" OWNER TO postgres;

ALTER TABLE public."Surveys" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Surveys_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


INSERT INTO public."Answers" (id, "AnswerText", "QuestionId") VALUES
(1, 'Москва', 1),
(2, 'Московская область', 1),
(3, 'Санкт-Петербург', 1),
(4, 'Ленинградская область', 1),
(5, 'От 10 до 18', 2),
(6, 'От 18 и далее', 2);


-- Вставка данных в таблицу Interviews
INSERT INTO public."Interviews" (id, "UserName", "SurveyId") VALUES
(1, 'Иван Иванов', 1);


-- Вставка данных в таблицу Questions
INSERT INTO public."Questions" (id, "QuestionText", "NextQuestionId", "SurveyId", "ResultId") VALUES
(1, 'В каком регионе Вы проживаете?', 2, 1, NULL),
(2, 'Ваш возраст', NULL, 1, NULL);

-- Вставка данных в таблицу Surveys
INSERT INTO public."Surveys" (id, "SurveyText") VALUES
(1, 'Личный опрос');


SELECT pg_catalog.setval('public."Answers_id_seq"', 7, false);


SELECT pg_catalog.setval('public."Interviews_id_seq"', 2, false);

SELECT pg_catalog.setval('public."Questions_id_seq"', 3, false);


SELECT pg_catalog.setval('public."Results_id_seq"', 1, true);


SELECT pg_catalog.setval('public."Surveys_id_seq"', 2, false);



ALTER TABLE ONLY public."Answers"
    ADD CONSTRAINT "PK_Answers" PRIMARY KEY (id);


ALTER TABLE ONLY public."Interviews"
    ADD CONSTRAINT "PK_Interviews" PRIMARY KEY (id);


ALTER TABLE ONLY public."Questions"
    ADD CONSTRAINT "PK_Questions" PRIMARY KEY (id);


ALTER TABLE ONLY public."Results"
    ADD CONSTRAINT "PK_Results" PRIMARY KEY (id);


ALTER TABLE ONLY public."Surveys"
    ADD CONSTRAINT "PK_Surveys" PRIMARY KEY (id);


CREATE INDEX "IX_Answers_QuestionId" ON public."Answers" USING btree ("QuestionId");


CREATE INDEX "IX_Interviews_SurveyId" ON public."Interviews" USING btree ("SurveyId");


CREATE UNIQUE INDEX "IX_Questions_ResultId" ON public."Questions" USING btree ("ResultId");

CREATE INDEX "IX_Questions_SurveyId" ON public."Questions" USING btree ("SurveyId");


CREATE INDEX "IX_Results_AnswerId" ON public."Results" USING btree ("AnswerId");


CREATE INDEX "IX_Results_InterviewId" ON public."Results" USING btree ("InterviewId");

ALTER TABLE ONLY public."Answers"
    ADD CONSTRAINT "FK_Answers_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES public."Questions"(id) ON DELETE CASCADE;


ALTER TABLE ONLY public."Interviews"
    ADD CONSTRAINT "FK_Interviews_Surveys_SurveyId" FOREIGN KEY ("SurveyId") REFERENCES public."Surveys"(id) ON DELETE CASCADE;

ALTER TABLE ONLY public."Questions"
    ADD CONSTRAINT "FK_Questions_Results_ResultId" FOREIGN KEY ("ResultId") REFERENCES public."Results"(id);

ALTER TABLE ONLY public."Questions"
    ADD CONSTRAINT "FK_Questions_Surveys_SurveyId" FOREIGN KEY ("SurveyId") REFERENCES public."Surveys"(id) ON DELETE CASCADE;


ALTER TABLE ONLY public."Results"
    ADD CONSTRAINT "FK_Results_Answers_AnswerId" FOREIGN KEY ("AnswerId") REFERENCES public."Answers"(id) ON DELETE CASCADE;

